### ISSUE TITLE
Errno 19 can't find any contactless devices

### ISSUE THREAD

**Issue by papapepo** [ElevenPaths/HomePWN#7]
Hello, I'm using a Raspberry pi 0w and a pn532. I have tried contacting it via uart, i2c and spi but I can't get it to work. Any idea what my issue may be? I run load nfc/setup but the sistem doesn't recognize the Pn532...

**Comment by lucferbux** [comment]
Hi, 

I haven't tried the pn532 chip and I can't test it now. However, that module is a wrap of the nfcpy project, I will leave you an [issue related to the pn532 in their repository](https://github.com/nfcpy/nfcpy/issues/32), hope it helps.
If not, I should suggest you open the issue in the[ nfcpy Github](https://github.com/nfcpy/nfcpy) as they might help you better.
Please, if you find the solution leave here a comment in order to keep track of the issues that might help other users.
